#########################
## Sample Sass Lint File
#########################
# Linter Options
options:
  # Don't merge default rules
  merge-default-rules: false
  # Set the formatter to 'html'
  formatter: html
  # Output file instead of logging results
  output-file: 'linters/sass-lint.html'
  # Raise an error if more than 50 warnings are generated
  max-warnings: 50
# File Options
files:
  include: 'src/sass/**/*.s+(a|c)ss'
  ignore:
    - 'sass/vendor/**/*.*'
# Rule Configuration
rules:
  attribute-quotes: 1
  brace-style:
    - 2
    -
      style: 1tbs
  empty-line-between-blocks: 1
  extends-before-mixins: 2
  extends-before-declarations: 2
  final-newline: 1
  force-attribute-nesting: 1
  force-element-nesting: 1
  force-pseudo-nesting: 1
  hex-notation:
    - 2
    -
      style: uppercase

  indentation:
    - 2
    -
      size: 2

  leading-zero: 1
  mixins-before-declarations:
    - 2
    -
      exclude:
        - breakpoint
        - mq

  no-debug: 1
  no-ids: 2
  no-important: 2
  no-warn: 1
  placeholder-in-extend: 2
  property-sort-order:
    - 1
    -
      order: alphabetical
      ignore-custom-properties: true

  pseudo-element: 1
  shorthand-values:
    - 1
    -
      allowed-shorthands:
        - 1

  url-quotes: 1

  variable-for-property:
    - 2
    -
      properties:
        - margin
        - color
        - content

  zero-unit: 1